// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppEF.AdventureS.Ef;

#nullable disable

namespace WebAppEF.AdventureS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250612160539_AddUserGuid")]
    partial class AddUserGuid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAppEF.AdventureS.Ef.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Role", "mad");
                });

            modelBuilder.Entity("WebAppEF.AdventureS.Ef.RoleTypes", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("RoleDescription")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoleTypes", "mad");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleDescription = "Administrator with full access to the system.",
                            RoleName = "Admin",
                            RoleType = 0
                        },
                        new
                        {
                            Id = 2,
                            RoleDescription = "Developer with access to development tools and resources.",
                            RoleName = "Developer",
                            RoleType = 1
                        },
                        new
                        {
                            Id = 3,
                            RoleDescription = "Manager with access to management tools and resources.",
                            RoleName = "Manager",
                            RoleType = 2
                        },
                        new
                        {
                            Id = 4,
                            RoleDescription = "Tester with acces to some internal resources.",
                            RoleName = "Tester",
                            RoleType = 3
                        });
                });

            modelBuilder.Entity("WebAppEF.AdventureS.Ef.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserGuid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User", "mad");
                });

            modelBuilder.Entity("WebAppEF.AdventureS.Ef.User", b =>
                {
                    b.HasOne("WebAppEF.AdventureS.Ef.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebAppEF.AdventureS.Ef.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
